name: PR Checks
on: pull_request
jobs:
  checks:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: gamebox-web/package-lock.json

      - name: Install dependencies
        working-directory: ./gamebox-web
        run: npm ci

      - name: Type check
        working-directory: ./gamebox-web
        run: npm run typecheck

      - name: Security scan
        working-directory: ./gamebox-web
        run: npm run security-scan

      - name: Build
        working-directory: ./gamebox-web
        run: npm run build
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Supabase CLI
        run: npm i -g supabase

      - name: Link preview DB
        if: ${{ secrets.PREVIEW_PROJECT_REF }}
        working-directory: ./gamebox-web
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
        run: |
          supabase link --project-ref ${{ secrets.PREVIEW_PROJECT_REF }}
          supabase db push
          supabase db seed

      - name: Install Playwright deps
        working-directory: ./gamebox-web
        run: npx playwright install --with-deps

      - name: Start preview server
        working-directory: ./gamebox-web
        run: |
          npm run build
          npm run start &
          sleep 10
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.PREVIEW_SUPABASE_URL || secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.PREVIEW_SUPABASE_ANON_KEY || secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.PREVIEW_SUPABASE_SERVICE_KEY || secrets.SUPABASE_SERVICE_ROLE_KEY }}

      - name: Smoke tests
        working-directory: ./gamebox-web
        env: 
          BASE_URL: http://localhost:3000
        run: npm run test:smoke

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with: 
          name: playwright-report
          path: gamebox-web/playwright-report

      - name: Comment PR with results
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            let comment = '## 🧪 PR Checks Results\n\n';
            
            // Check if Playwright report exists
            const reportPath = 'gamebox-web/playwright-report/index.html';
            if (fs.existsSync(reportPath)) {
              comment += '✅ **Playwright Tests**: [View Report](artifact://playwright-report)\n\n';
            } else {
              comment += '⚠️ **Playwright Tests**: No report generated\n\n';
            }
            
            comment += '### Next Steps:\n';
            comment += '- Review any test failures in the Playwright report\n';
            comment += '- Ensure all security scans pass\n';
            comment += '- Verify build completes successfully\n';
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
